class Users:
    id_ = "_id"
    id = "id"
    user_id = "user_id"
    manager_id = "manager_id"
    name = "name"
    firstname = "firstname"
    lastname = "lastname"
    password = "password"
    email = "email"
    new_pswrd = "New Password"
    hashed_password = "hashed_password"
    role = "role"
    public_key = "public_key"
    private_key = "private_key"
    company = "company"
    warehouse = "warehouse"
    order_id = "order_id"
    orders = "orders"
    telephone = "telephone"
    deletionDate = "deletionDate"
    user_address = "user_address"
    zip_code ="zip_code"
    street = "street"
    city="city"
    region="region"
    country="country"
    is_confirmed="is_confirmed"


class Roles:
    admin = "admin"
    director = "director"
    salesman = "salesman"
    manager = "manager"
    user = "user"
    employee = "employee"
    controller = "controller"
    dispatcher = "dispatcher"
    warehouseman = "warehouseman"
    loader = "loader"
    client = "client"
    workWOMEN = "workWOMEN"


class Token:
    authorization = "Authorization"
    expires = "expires"
    access_token = "access_token"
    properties = "properties"
    payload = "payload"
    refresh_token="refresh_token"


class Messages:
    message = "message"
    created = "User was created successfully"
    deleted = "User was deleted successfully"
    pswrd_chngd = "Password was changed successfully"
    keys_chngd = "Key pair was changed successfully"
    user_allreay_exists = "User allready exist"
    user_not_found = "User not found"
